apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistenceVolume.name }}
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistenceVolume.storage }}